### ISSUE TITLE
[fullstory] District filter remains open after interacting with other parts of the page

### ISSUE THREAD

**Issue by sychang** [Recidiviz/pulse-dashboard#596] opened 2020-11-02 04:12 UTC
**What needs to be done? Why does it need to be done?**
From viewing a Fullstory session, it appears that one users's district filter remains open even after they click on the case type filter and interact with other parts of the page. I did not see this behavior occur for any other users. The user was using IE11.

![image.png](https://images.zenhubusercontent.com/5ec1f17e7e863d6fd9e7e91c/36b9e41c-0f3d-4da2-afc6-86fb3c2d186b)

**Additional context**
Fullstory is sometimes a little janky, so I'm not sure if this was actually occurring, or the video was off. Can close if this ends up being not reproducible.

**Comment by jovergaag** [comment] 2020-11-03 02:28
@Wmaileq It looks like in IE11 the district filter is not closing when clicking anywhere else on the page. I believe this bug can be resolved by closing the menu on a click outside.

**Comment by Wmaileq** [comment] 2020-11-03 15:29
Tested in IE11 on Windows 10, 8.1, 8, 7: couldn't reproduce.

Seems like this bug reproduces only in IE11 Metro which comes with Windows 8.1

**Comment by Wmaileq** [comment] 2020-11-04 15:21
Tried one more time: 
[ie11_district_dropdown_test.mp4.zip](https://github.com/Recidiviz/pulse-dashboard/files/5488655/ie11_district_dropdown_test.mp4.zip)

Could not reproduce it :-(

**Comment by jovergaag** [comment] 2020-11-04 21:46
OK. I'll take a look at it. I'm able to reproduce it.

**Comment by jovergaag** [comment] 2020-11-06 23:01
@Wmaileq I did more looking into this today. I am able to reproduce it on any of my emulated IE11 browsers on dashboard-staging.recidiviz.org. But on localhost I also cannot reproduce it! Uff. This must be a difference in how webpack is bundling vs how react-scripts is built for deploys. 

Seems like this is in my court now...

cc: @jessex

**Comment by jessex** [comment] 2020-11-06 23:05
If it's a Webpack vs react-scripts difference, I think you should be able to reproduce locally by doing `yarn build-staging && firebase serve`. That wouldn't work right now for @Wmaileq but it would work for you, @jovergaag

**Comment by jovergaag** [comment] 2020-11-07 00:39
Yes exactly, that explains why @Wmaileq was not able to reproduce, it was not an environment issue. 

Confirmed. Reproducible from `firebase serve`. I'll take this one over.

**Closed** 2020-11-20 18:47 UTC
Labels: Team: Lantern
