### ISSUE TITLE
[US_ND] [Workflows] Downloaded or printed form missing some data

### ISSUE THREAD

**Issue by clayciat** [Recidiviz/pulse-dashboard#2192] opened 2022-08-18 19:28 UTC
- Judicial district is missing
- Entire header missing when docx file is loaded into google drive I.e. starts at: “[1] The Defendant, being first…”
- Some form fields aren’t autofilling for certain users (eg. the field next to [3] for each of Mar Dee Spurgeon’s clients, the field next to [3] and under 1a for Dan Strandberg’s clients) - may not be an issue, but the fields autofill for other officers so just wanted to flag

**Comment by daschi** [comment] 2022-08-18 22:32
The first and second bullet points should be fixed by PR #2186, I'm not able to reproduce the second bullet point.

**Closed** 2022-08-25 20:42 UTC
Labels: bug bash
