### ISSUE TITLE
[US_ID] Possible bug in sex offender caseload logic / compliance standards

### ISSUE THREAD

**Issue by cawarren** [Recidiviz/pulse-dashboard#1359] opened 2021-09-29 18:12 UTC
_Note: Not as high-pri as other Day Zero issues_

From @sychang 

> There might be a bug in the case triage “sex offense caseload logic where level X people need to have 2 F2F contacts every month, but Case Triage only shows them needing one every 3 months.” I can’t reproduce this looking at Bethany Lyons’ caseload, but is worth verifying that our sex offense level HIGH (level 3) logic is recommending 1 contact every 15 days.

@ohaibbq could you check this out? Sorry we don't have a full bug report rundown on this, it was something Serena mentioned in passing late last night, and we didn't have enough time to test more before she had to leave this morning for the outer field offices.

**Comment by Catacola** [comment] 2021-10-04 16:57
Duplicate of #1358. Closing.

**Closed by Catacola** 2021-10-04 16:57 UTC
