### ISSUE TITLE
New user redirect loop

### ISSUE THREAD

**Issue by ohaibbq** [Recidiviz/pulse-dashboard#682] opened 2020-12-29 18:50 UTC
**Describe the bug**
Upon registering as a new user, the browser gets stuck in a redirect loop. When request auth information from auth0, which returns `unauthorized`, then the page reloads and the process repeats. Once the email is verified, the app behaves correctly.

**To Reproduce**
1. Sign up for a new Dashboard account

**Expected behavior**
A prompt to verify email is shown or I am signed into the app

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]: Mac 
 - Browser [e.g. chrome, edge]: Chrome

**Comment by jessex** [comment] 2021-01-05 01:01
This seems like a regression. The proper behavior is that until you are verified, you are continually redirected to the [`/verify` page](https://dashboard.recidiviz.org/verify). I think the way I originally did this via Auth0 rules was overly complex, and we settled on a better approach for the Covid app, which manages the verification redirect directly in React.

@jovergaag, could you or Daniela take a look into this and confirm that you can reproduce it? I know we have recently invited new users for PA and will be inviting more users this quarter, so I want to make sure we know what the current situation is.

**Comment by jovergaag** [comment] 2021-01-05 02:34
@jessex I can reproduce it. I'll take a look at it tomorrow!

**Comment by jovergaag** [comment] 2021-01-06 01:08
This is due to the 'Domain whitelist for Admin panel' rule which only exists in the `recidiviz` tenant, not `recidiviz-dev`. It is overriding the redirect callback when the `user.email_verified = false`.

Copying that new rule to `recidiviz-dev` to reproduced the error.  I was able to modify that rule to pass through unverified users which successfully redirects the dashboard to the verify page, yay. I am checking with @nbhargava to test this updated rule out before making the change on the `recidiviz` tenant.

**Comment by nbhargava** [comment] 2021-01-06 01:18
Chatted with @jovergaag and this was a snafu on my end back when I was setting up the Admin panel. Best course of action is to delete the offending rule!

Thanks @jovergaag!!

**Comment by jovergaag** [comment] 2021-01-06 01:26
Deleted! Thanks @nbhargava

**Closed by jovergaag** 2021-01-06 01:26 UTC
Labels: Subject: Authentication, Subject: UX, Team: Lantern, Type: Bug
